Update validate-pr-commit-message.yml

diff --git a/.github/workflows/validate-pr-commit-message.yml b/.github/workflows/validate-pr-commit-message.yml
--- a/.github/workflows/validate-pr-commit-message.yml
+++ b/.github/workflows/validate-pr-commit-message.yml
@@ -17,7 +17,20 @@ jobs:
           
         run: |
           # Fetch the pull request and checkout the merge commit
-          echo $PR_NUMBER
+          git fetch origin pull/${PR_NUMBER}/merge:pr-${PR_NUMBER}
+          git checkout pr-${PR_NUMBER}
+
+          # Define your commit message pattern (e.g., start with "test:")
+          PATTERN="^(feat|fix|chore|docs|style|refactor|perf|test)(\([^)]+\))?(\!)?\: .+"
+          
+          # Get the squashed commit message
+          COMMIT_MESSAGE=$(git log --format=%B -n 1 HEAD)
+          
+          if ! [[ "$COMMIT_MESSAGE" =~ $PATTERN ]]; then
+            echo "Invalid squashed commit message: $COMMIT_MESSAGE"
+            exit 1
+          fi
+
         continue-on-error: false
 
       - name: Set Status Check
